<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIaog6T\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIaog6T/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIaog6T.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIaog6T\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIaog6T\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIaog6T',
    'container.build_id' => '41e9f381',
    'container.build_time' => 1635870198,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIaog6T');
