<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTqTYxA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTqTYxA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTqTYxA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTqTYxA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTqTYxA\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTqTYxA',
    'container.build_id' => '53839ac2',
    'container.build_time' => 1636453103,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTqTYxA');
