<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Enseigner extends \App\Entity\Enseigner implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'startAt', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'endAt', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'temoin', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'poste'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'startAt', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'endAt', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'temoin', '' . "\0" . 'App\\Entity\\Enseigner' . "\0" . 'poste'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Enseigner $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getStartAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartAt', []);

        return parent::getStartAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartAt(\DateTime $startAt): \App\Entity\Enseigner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartAt', [$startAt]);

        return parent::setStartAt($startAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndAt(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndAt', []);

        return parent::getEndAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndAt(\DateTime $endAt): \App\Entity\Enseigner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndAt', [$endAt]);

        return parent::setEndAt($endAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation(string $observation): \App\Entity\Enseigner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$observation]);

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemoin(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemoin', []);

        return parent::getTemoin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemoin(?\App\Entity\Users $temoin): \App\Entity\Enseigner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemoin', [$temoin]);

        return parent::setTemoin($temoin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste(): ?\App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste(?\App\Entity\Postes $poste): \App\Entity\Enseigner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$poste]);

        return parent::setPoste($poste);
    }

}
